swagger: '2.0'

# basic meta information
info:
  title: Kio API
  version: '0.2'
  description: Kio is STUPS' application registry.

externalDocs:
  description: STUPS overview
  url: http://zalando-stups.github.io/

# technical configuration
basePath: /
produces:
- application/json
consumes:
- application/json

paths:

  # applications

  '/apps':
    get:
      summary: list applications
      description: |
        Lists all registered applications.
      tags:
        - Applications
      operationId: 'org.zalando.stups.kio.api/read-applications'
      parameters:
        - name: search
          in: query
          description: "Search term for application filtering."
          type: string
          required: false
      responses:
        200:
          description: List of all applications
          schema:
            type: array
            items:
              $ref: '#/definitions/ApplicationSummaryRead'
        default:
          $ref: '#/responses/Error'

  '/apps/{application_id}':
    get:
      summary: read application
      description: |
        Returns details about one application
      tags:
      - Applications
      operationId: 'org.zalando.stups.kio.api/read-application'
      parameters:
      - $ref: '#/parameters/ApplicationID'
      responses:
        200:
          description: Details of one application
          schema:
            $ref: '#/definitions/ApplicationDetailsRead'
        404:
          description: Not found
        default:
          $ref: '#/responses/Error'

    put:
      summary: create or update application
      description: |
        Creates or updates an application.
      tags:
      - Applications
      operationId: "org.zalando.stups.kio.api/create-or-update-application!"
      parameters:
      - $ref: '#/parameters/ApplicationID'
      - name: application
        in: body
        description: Application details that will be saved.
        schema:
          $ref: '#/definitions/ApplicationWrite'
        required: true
      responses:
        200:
          description: Application was saved.
        default:
          $ref: '#/responses/Error'

  # approval types
  '/apps/{application_id}/approvals':
    get:
      summary: list used approval types
      description: |
        Returns all used approval types for an application.
      tags:
        - Applications
      operationId: 'org.zalando.stups.kio.api/read-application-approvals'
      parameters:
      - $ref: '#/parameters/ApplicationID'
      responses:
        200:
          description: List of approvals
          schema:
            type: array
            items:
              type: string
        404:
          description: Not found
        default:
          $ref: '#/responses/Error'

  # versions

  '/apps/{application_id}/versions':
    get:
      summary: list versions
      description: |
        Returns a list of all versions of an application.
      tags:
        - Versions
      operationId: 'org.zalando.stups.kio.api/read-versions-by-application'
      parameters:
      - $ref: '#/parameters/ApplicationID'
      responses:
        200:
          description: List of versions
          schema:
            type: array
            items:
              $ref: '#/definitions/VersionSummaryRead'
        404:
          description: Not found
        default:
          $ref: '#/responses/Error'

  '/apps/{application_id}/versions/{version_id}':
    get:
      summary: read version
      description: |
        Returns a list of all versions of an application.
      tags:
        - Versions
      operationId: 'org.zalando.stups.kio.api/read-version-by-application'
      parameters:
      - $ref: '#/parameters/ApplicationID'
      - $ref: '#/parameters/VersionID'
      responses:
        200:
          description: Returns detailed information
          schema:
            $ref: '#/definitions/VersionDetailsRead'
        404:
          description: Not found
        default:
          $ref: '#/responses/Error'

    put:
      summary: create or update version
      description: |
        Creates or updates a version.
      tags:
      - Versions
      operationId: "org.zalando.stups.kio.api/create-or-update-version!"
      parameters:
      - $ref: '#/parameters/ApplicationID'
      - $ref: '#/parameters/VersionID'
      - name: version
        in: body
        description: Version details that will be saved.
        schema:
          $ref: '#/definitions/VersionWrite'
        required: true
      responses:
        200:
          description: Version was saved.
        default:
          $ref: '#/responses/Error'

  # approvals

  '/apps/{application_id}/versions/{version_id}/approvals':
    get:
      summary: list approvals
      description: |
        Returns a list of all approvals of a version.
      tags:
        - Approvals
      operationId: 'org.zalando.stups.kio.api/read-approvals-by-version'
      parameters:
      - $ref: '#/parameters/ApplicationID'
      - $ref: '#/parameters/VersionID'
      responses:
        200:
          description: List of approvals
          schema:
            type: array
            items:
              $ref: '#/definitions/ApprovalRead'
        404:
          description: Not found
        default:
          $ref: '#/responses/Error'

    post:
      summary: approve version
      description: |
        Approves a version.
      tags:
      - Approvals
      operationId: "org.zalando.stups.kio.api/approve-version!"
      parameters:
      - $ref: '#/parameters/ApplicationID'
      - $ref: '#/parameters/VersionID'
      - name: approval
        in: body
        description: Approval information
        schema:
          $ref: '#/definitions/ApprovalWrite'
        required: true
      responses:
        200:
          description: Version was approved.
        default:
          $ref: '#/responses/Error'

# definitions

parameters:
  ApplicationID:
    name: application_id
    in: path
    type: string
    description: ID of the application
    required: true
    pattern: "^[a-z][a-z0-9-]*[a-z0-9]$"

  VersionID:
    name: version_id
    in: path
    type: string
    description: ID of the version
    required: true
    pattern: "^[a-zA-Z0-9][a-zA-Z0-9.-]*[a-zA-Z0-9]$"

responses:
  Error:
    description: An error occured.
    schema:
      $ref: '#/definitions/Error'

definitions:
  ApplicationSummaryRead:
    properties:
      id:
        type: string
        description: Unique identifier of the application
      team_id:
        type: string
        description: ID of the team, responsible for this application
      name:
        type: string
        description: A human-readable name of the application
      subtitle:
        type: string
        description: Subtitle of the application
      service_url:
        type: string
        description: URL of the service
      matched_rank:
        type: float
        description: Search result rank for ordering
      matched_description:
        type: string
        description: Text fragments of the search result
    required:
      - id
      - team_id
      - name
      - subtitle
      - service_url
    example:
      id: kio
      team_id: stups
      name: Kio
      subtitle: Application Registry
      service_url: https://kio.example.com/

  ApplicationDetailsRead:
    properties:
      id:
        type: string
        description: Unique identifier of the application
      team_id:
        type: string
        description: ID of the team, responsible for this application
      active:
        type: boolean
        description: If the application is active
      name:
        type: string
        description: A human-readable name of the application
      subtitle:
        type: string
        description: An additional title for the application
      description:
        type: string
        description: Purpose of this application
      service_url:
        type: string
        description: URL of the application
      scm_url:
        type: string
        description: URL of SCM repository
      documentation_url:
        type: string
        description: URL of documentation
      specification_url:
        type: string
        description: URL of the specification tool
    example:
      id: kio
      team_id: stups
      active: true
      name: Kio
      subtitle: STUPS' application registry
      description: Kio manages all application base information.
      service_url: https://kio.example.com/
      scm_url: https://github.com/zalando-stups/kio.git
      documentation_url: https://github.com/zalando-stups/kio
      specification_url: https://github.com/zalando-stups/kio/issues

  ApplicationWrite:
    properties:
      team_id:
        type: string
        description: ID of the team, responsible for this application
      active:
        type: boolean
        description: if the application is active
      name:
        type: string
        description: A human-readable name
        minLength: 1
      subtitle:
        type: string
        description: An additional title for the application
        minLength: 1
      description:
        type: string
        description: Purpose of this application
      service_url:
        type: string
        description: URL of the application
      scm_url:
        type: string
        description: URL of SCM repository
      documentation_url:
        type: string
        description: URL of documentation
      specification_url:
        type: string
        description: URL of the specification tool
    required:
    - team_id
    - active
    - name
    - subtitle
    - description
    example:
      team_id: stups
      active: true
      name: Kio
      subtitle: STUPS' application registry
      description: Kio manages all application base information.
      service_url: https://kio.example.com/
      scm_url: https://github.com/zalando-stups/kio.git
      documentation_url: https://github.com/zalando-stups/kio
      specification_url: https://github.com/zalando-stups/kio/issues
  VersionSummaryRead:
    properties:
      id:
        type: string
        description: Unique identifier of the version
      application_id:
        type: string
        description: ID of the version's application
      artifact:
        type: string
        description: Software artifact reference of this version
    example:
      id: 1.0
      application_id: kio
      artifact: docker://stups/kio:1.0

  VersionDetailsRead:
    properties:
      id:
        type: string
        description: Unique identifier of the version
      application_id:
        type: string
        description: ID of the version's application
      artifact:
        type: string
        description: Software artifact reference of this version
      notes:
        type: string
        description: Release notes in Markdown format
    example:
      id: 1.0
      application_id: kio
      artifact: docker://stups/kio:1.0
      notes: |
        **Release 1.0**

        * initial commit
        * bugfixes

  VersionWrite:
    properties:
      artifact:
        type: string
        description: Software artifact reference of this version
      notes:
        type: string
        description: Release notes in Markdown format
    required:
    - artifact
    example:
      artifact: docker://stups/kio:1.0
      notes: |
        **Release 1.0**

        * initial commit
        * bugfixes

  ApprovalRead:
    properties:
      application_id:
        type: string
        description: ID of the application
      version_id:
        type: string
        description: ID of the application's version
      approval_type:
        type: string
        description: Kind of approval like 'TESTED' or 'REVIEWED'.
      user_id:
        type: string
        description: ID of the user who approved the version
      approved_at:
        type: string
        format: date-time
        description: Point in time when the version was approved
      notes:
        type: string
        description: Some hints on what was approved
    example:
      application_id: kio
      version_id: 1.0
      approval_type: TESTED
      user_id: tobi
      approved_at: '2015-04-25T16:25:00'
      notes: I tested this kio version carefully.

  ApprovalWrite:
    properties:
      notes:
        type: string
        description: Some hints on what was approved
      approval_type:
        type: string
        description: Kind of approval like 'TESTED' or 'REVIEWED'.
    required:
    - approval_type
    example:
      notes: I tested this kio version carefully.
      approval_type: TESTED

  Error:
    type: object
    properties:
      message:
        type: string
    example:
      message: Internal Server Error
